added hmi-extraction-service to orchestration
DARPA-ASKEM/orchestration pull request #148
Opened 2023-05-16 13:23 UTC by tangopapatime

# Description

Added the new `hmi-extraction-service`

2023-05-16 19:10 UTC, tangopapatime commented
@dgauldie @chris-dickson Let me know if this looks good.

2023-05-17 15:12 UTC, bigglesandginger requested changes
The staging might need more work to establish the env for the deployemnt, and with that secrets.  Obviously Production does not exist, but I assume this is "stage 1" get working iun dev and staging, then iron out the creases and create the production templates

2023-05-17 15:12 UTC, bigglesandginger commented on kubernetes/base/services/hmi-extraction-service/hmi-extraction-service-deployment.yaml
> +              value: terarium123
If these are not common to ALL deployments then they should not be in the base.  Look at hmi-server-deployment as an example - the base has no `env` section, where as the overlays do

2023-05-17 15:12 UTC, bigglesandginger commented on kubernetes/base/services/hmi-extraction-service/hmi-extraction-service.yaml
> +    software.uncharted.terarium/service: hmi-extraction
service no longer "desired" - delete line

2023-05-17 15:12 UTC, bigglesandginger commented on kubernetes/base/services/hmi-extraction-service/hmi-extraction-service-deployment.yaml
> +    software.uncharted.terarium/service: hmi-extraction
service no longer "desired" - delete line

2023-05-17 15:12 UTC, bigglesandginger commented on kubernetes/overlays/dev/local/services/hmi-extraction-service/kustomization.yaml
> +  - hmi-extraction-service.yaml
insert the patch for the env vars for `...deployment.yaml` here

2023-05-17 15:12 UTC, bigglesandginger commented on kubernetes/overlays/prod/overlays/askem-staging/services/hmi-extraction-service/hmi-extraction-service.yaml
> +---
This file does not appear to be referenced by an `kustomization.yaml` file.

2023-05-17 15:27 UTC, tangopapatime commented on kubernetes/base/services/hmi-extraction-service/hmi-extraction-service-deployment.yaml
> +              value: terarium123
this should be common to ALL deployments afaik just like the new message queue.

2023-05-17 17:29 UTC, tangopapatime reviewed
should be good to go.

2023-05-17 17:32 UTC, bigglesandginger commented on kubernetes/overlays/dev/local/services/hmi-extraction-service/kustomization.yaml
> +  - hmi-extraction-service-deployment.yaml
As you are not adding env vars - this line is not needed

2023-05-17 17:34 UTC, bigglesandginger approved these changes

2023-05-17 17:41 UTC, merged