chore: local llm
DARPA-ASKEM/orchestration pull request #203
Opened 2023-07-11 21:11 UTC by dgauldie

# Description

Please include a summary of the changes and the related issue.

Resolves #(issue)

2023-07-11 21:21 UTC, YohannParis approved these changes

2023-07-11 23:46 UTC, YohannParis approved these changes

2023-07-12 12:55 UTC, merged

2023-07-12 12:56 UTC, bigglesandginger requested changes

2023-07-12 12:56 UTC, bigglesandginger commented on kubernetes/overlays/prod/base/services/pyciemss-service/pyciemss-api-deployment.yaml
> +              value: http://data-service:3020
This is inconsistent with dev (which does not have the protocol) - does this matter, should they be consistent?