feat: add ingress for mit-tr
DARPA-ASKEM/orchestration pull request #265
Opened 2023-08-16 18:59 UTC by YohannParis

# Description

* Add an ingress endpoint for `mit-tr` service on staging.

2023-08-16 20:47 UTC, bigglesandginger commented on kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml
> +                  number: 8000
It looks like the service defines it as 4046 for some reason.

2023-08-16 21:49 UTC, YohannParis commented on kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml
> +                  number: 8000
Where and how did you saw that? Maybe it's on the bake file?

2023-08-16 22:11 UTC, bigglesandginger commented
It is in the service definition for “mit-tr” in the base - not at a
computer at the moment so cannot point to the exact file

On Wed, Aug 16, 2023 at 5:49 PM Yohann Paris ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> kubernetes/overlays/prod/overlays/askem-staging/ingress/private-web-ingress.yaml
> <https://github.com/DARPA-ASKEM/orchestration/pull/265#discussion_r1296463956>
> :
>
> > @@ -67,6 +67,17 @@ spec:
>                  port:
>                    number: 3981
>
> +    - host: "mit-tr.staging.terarium.ai"
> +      http:
> +        paths:
> +          - path: /
> +            pathType: Prefix
> +            backend:
> +              service:
> +                name: mit-tr
> +                port:
> +                  number: 8000
>
> Where and how did you saw that? Maybe it's on the bake file?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DARPA-ASKEM/orchestration/pull/265#discussion_r1296463956>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABHRFBJCYHMSAFH5ULTYT4TXVU57VANCNFSM6AAAAAA3S6ZG74>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-08-21 14:24 UTC, bigglesandginger requested changes

2023-08-21 14:30 UTC, bigglesandginger approved these changes

2023-08-21 14:34 UTC, merged