ci: updated publish scripts to work the same way as the TERArium repo
DARPA-ASKEM/orchestration pull request #27
Opened 2022-11-17 18:13 UTC by dgauldie

# Description

These CI scripts should work the same way as TERArium

Resolves #(issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] CI change

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide reproduction instructions and list any relevant details for your test configuration

- [ ] need to manually test 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-17 19:11 UTC, YohannParis commented
I don't understand the purpose of the bake file in this repo?
Shouldn't they go to the `.github` repo?

2022-11-18 14:10 UTC, Nithos requested changes
I think we should discuss this further.

2022-11-18 14:10 UTC, Nithos commented on .github/workflows/publish.yaml
> +  # Run yaml file lint
Remove these ones, the main `lint` does them all here along with k8s. Terarium was split b/c it has a slightly different lint strategy (ie JS/TS linting etc..)

TLDR: remove `lint-yaml` `lint-docker`

2022-11-18 14:10 UTC, Nithos commented on .github/workflows/publish.yaml
> +      - lint-yaml
remove yaml and docker once the above is done as well

2022-11-18 14:10 UTC, Nithos commented on .github/workflows/bake-publish.yml
> -# This is a reusable workflow for building and publishing Docker images
This was meant as the reusable workflow... in theory Terarium should be using this but due to the extra builds that need to happen there I have not been able to do that yet.
IMO this is better if we just have docker files that need to be built... for Terarium ideally we would change to a multi build dockerfile that does the necessary builds within it rather than relying on external builds to happen and move the files over.

2022-11-22 19:53 UTC, dgauldie commented on .github/workflows/publish.yaml
> +      - lint-yaml
fixed

2022-11-22 20:08 UTC, dgauldie commented
this work is not needed

2022-11-22 20:08 UTC, closed without merging