2544 - Add gollm-taskrunner
DARPA-ASKEM/orchestration pull request #354
Opened 2024-01-30 16:38 UTC by kbirk

2024-01-30 19:48 UTC, YohannParis approved these changes
Is there a need to add an ingress like `gollm-taskrunnier.staging.terarium.ai` for this service? I know the logs will be available via `kubectl`.

2024-01-30 19:48 UTC, YohannParis commented on kubernetes/overlays/prod/overlays/askem-production/services/gollm-taskrunner/gollm-deployment.yaml
Why are you not defining the API key in the base service instead of here in the overlays?

2024-01-30 19:55 UTC, kbirk commented on kubernetes/overlays/prod/overlays/askem-production/services/gollm-taskrunner/gollm-deployment.yaml
I just copied what the original `gollm` stuff used D:

2024-01-30 20:02 UTC, dgauldie requested changes
I think you are missing the images in the customization files on prod and staging... and in check-latest

2024-01-31 21:14 UTC, YohannParis approved these changes
LGTM

2024-01-31 21:18 UTC, dgauldie approved these changes

2024-02-01 20:39 UTC, merged