April serivces adjustment
DARPA-ASKEM/orchestration pull request #388
Opened 2024-04-05 14:25 UTC by bigglesandginger

# Description

Please include a summary of the changes and the related issue.

Resolves #(issue)

2024-04-05 14:39 UTC, YohannParis requested changes
Let's wait post-evaluation

2024-04-05 14:39 UTC, YohannParis commented on kubernetes/deploy.sh
Why the double `shift`?

2024-04-05 14:39 UTC, YohannParis commented on kubernetes/overlays/prod/overlays/askem-staging/services/skema/skema-text-reading-deployment.yaml
Do we still need `skema-text-reading` to be on its own node?
This is just a matter of speed right? or does it needs that full node to be able to run?

2024-04-05 14:56 UTC, bigglesandginger commented on kubernetes/deploy.sh
`shift` in bash moves the parameter pointer along (effectively renumbering the parameters ignoring the shifted ones).  This is useful when looping over the command arguments (basically moving to the next one).  However, you can see that sometimes (all the time) I get the Environment (which is the next parameter) and so must call an additional `shift` (there is a `shift` at the bottom of the loop, the done statement, as well for the current parameter) and in the case of encrypting or decrypting a single file I need to call yet another `shift`.  The code could have been written as 
```
COMMAND="encrypt"
ENVIRONMENT="$2"
shift
FILE_NAME="$2"
shift
;;
```
a question of which looks more ugly in an ugly language :)

2024-04-05 14:57 UTC, bigglesandginger commented on kubernetes/overlays/prod/overlays/askem-staging/services/skema/skema-text-reading-deployment.yaml
`skema-text-reading` uses 8GB RAM on start up - does it use more? - the previous version did use approx 20GB RAM

2024-04-05 14:58 UTC, bigglesandginger commented on kubernetes/overlays/prod/overlays/askem-staging/services/skema/skema-text-reading-deployment.yaml
and this is definitely a question of RAM not cpu

2024-04-12 13:23 UTC, YohannParis approved these changes

2024-04-12 13:23 UTC, YohannParis commented on kubernetes/overlays/prod/overlays/askem-production/hmi/server/hmi-server-deployment.yaml
> +      #     effect: "NoSchedule"
```suggestion
```

2024-04-12 13:28 UTC, bigglesandginger commented on kubernetes/overlays/prod/overlays/askem-production/hmi/server/hmi-server-deployment.yaml
> +      #     effect: "NoSchedule"
I have no idea what is being suggested here - when I commented out the lines VIM added the hashes - but honestly I think we should delete these...

2024-04-12 13:29 UTC, merged