Add cosmos to kube
DARPA-ASKEM/orchestration pull request #411
Opened 2024-05-31 14:55 UTC by bigglesandginger

# Description

Please include a summary of the changes and the related issue.

Resolves #(issue)

2024-06-03 15:57 UTC, YohannParis approved these changes

2024-06-05 19:13 UTC, dgauldie commented on kubernetes/overlays/prod/overlays/askem-staging/kustomization.yaml
> +  # mira taskrunner
copy-paste error

2024-06-05 19:15 UTC, dgauldie approved these changes
other than that little copy/paste error, this looks good.

2024-06-05 19:15 UTC, dgauldie commented
you will need to fix some conflicts

2024-06-05 19:17 UTC, dgauldie requested changes
Can you add cosmos to the dev deployment now?

2024-06-29 00:35 UTC, dgauldie approved these changes

2024-07-03 13:14 UTC, merged