task: add a postgres for the terrarium application
DARPA-ASKEM/orchestration pull request #63
Opened 2023-01-18 20:53 UTC by chris-dickson

This adds a local postgres and provides the correct environment for connecting to RDS in staging and production via the hmi-server.  

Corresponding PR: https://github.com/DARPA-ASKEM/TERArium/pull/482

2023-01-18 22:24 UTC, YohannParis approved these changes

2023-01-18 22:29 UTC, YohannParis requested changes
You forgot to add it to the `down` command.
Or maybe replace `hmi-server` and `hmi-client` with `hmi-*`.

2023-01-19 15:38 UTC, bigglesandginger approved these changes
LGTM - from a staging/prod POV

2023-01-19 15:47 UTC, bigglesandginger commented on kubernetes/local/deploy-terarium.sh
> +	kubectl apply --filename 'hmi-postgres-*.yaml'
Really, the various containers should run, or exit if for some reason they cannot, then allow Kubernetes to restart a container.  This way hmi-server can launch before Keycloak, fail and exit, then relaunch.  When launching the full stack it often takes the hmi-server 2 attempts to get up and running due to the length of time it takes Keycloak to run.  But no true errors.

2023-01-20 18:26 UTC, chris-dickson commented
> * You forgot to add it to the `down` command. Or maybe replace `hmi-server` and `hmi-client` with `hmi-*`
I intentionally named them the way they are.  If you run `deploy-terarium stop hmi-server` it will kill the database as well which is not what you want.  You never want to stop that database so I think the scripts are fine the way they are.

2023-01-20 20:58 UTC, YohannParis commented
> > You forgot to add it to the `down` command. Or maybe replace `hmi-server` and `hmi-client` with `hmi-*`
> 
> I intentionally named them the way they are. If you run `deploy-terarium stop hmi-server` it will kill the database as well which is not what you want. You never want to stop that database so I think the scripts are fine the way they are.

I agree for `stop` command. But the `down` command is to turn off all your local k8 pods. 
I don't want to have to do `./deploy-terarium.sh down && ./deploy-terarium.sh stop hmi-database` every day.

2023-01-30 16:12 UTC, closed without merging